### PR TITLE
Initial windows build

### PR DESCRIPTION
**Pull request by s7726**
This gets it building under cygwin64 on windows.

This is by no means awesome, or even necessarily the right way to do it. But it builds, so it's a start.

It runs, but not so well, I tried it under the cygwin/X so not sure if that caused issues.

### CODE REVIEW

**Comment by mkeeter** [comment]
How did you get boost::python3 installed in this setup?

**Comment by paul70078** [comment]
Compiling works for met too but when executing I get a error:

This application failed to start because it could not find or load the Qt platform plugin "xcb".

Reinstalling the application may fix this problem.
      0 [main] antimony 57252 cygwin_exception::open_stackdumpfile: Dumping stack trace to antimony.exe.stackdump

**Comment by s7726** [comment]
@mkeeter I built everything under cygwin so I just installed the libboost_python3 and libboost_python3-devel stuff (cygwin also installed all the libboost libs for dependencies) and it worked no problem.

I imagine if you try to build without cygwin it may be harder to get boost setup. I know the last time I tried it was not fun.

**Comment by paul70078** [comment]
Seems to work with cygwin/X. Would like to have it without X-Server

**Comment by s7726** [comment]
Looks like a cygwin based build will require X. Next step, now that it
builds at all on Windows, is probably mingw, or maybe msvc.

**Comment by mkeeter** [comment]
mingw is probably the way to go, as msvc doesn't support C99 (which is used in the geometry kernel).

**Comment by s7726** [comment]
Would c++0x/11 not work?

**Comment by mkeeter** [comment]
There are parts of libfab that are pure C; not sure if anything would go wrong with a C++11 compiler applied to them.  Anyways, thanks for the PR -- I'll merge it in (though I'm going to factor the `qmake` stuff into a `WINDOWS` block shortly).

**Comment by s7726** [comment]
Can you do a cygwin block instead of just Windows? I'm not super familiar
with qmake. I think that would leave us setup for the potential mingw build.

**Comment by mkeeter** [comment]
You're correct; I've changed the block to `cygwin` (b7bcf5f)

**Pull request merged**
