### PR TITLE
Added BREW_HOME lookup for OSX builds

### PR DESCRIPTION
**Pull request by RMKD**
I had some trouble getting this to build with homebrew installed in userspace. This is a generalized version of my fix that lets users configure the paths via a BREW_HOME environment variable.

### CODE REVIEW

**Comment by mkeeter** [comment]
Thanks for the PR!

For some reason, this patch is applied against a revision that's 9 months old, and the organization of `.pro` files has changed since then.

Can you update your checkout of `develop` and re-apply these changes so that the patch can merge cleanly?

**Comment by RMKD** [comment]
Must have pulled upstream from master but not develop. This should merge cleanly now.

**Comment by mkeeter** [comment]
Great, thanks!

**Comment by mkeeter** [comment]
As it turns out, this is broken and fails whenever `BREW_HOME` is unset.
(*mea culpa* for not doing so much as a test-compile)

`$$(BREW_HOME)` is "look at this environmental variable;
`$${BREW_HOME}` is "look at the `qmake` variable".

This should be fixed in 504058592219a44f90bb153b6bd6b6ed8e232ed0.

@RMKD, can you confirm that it still works with a custom homebrew path?

**Pull request merged**
