### PR TITLE
Debian packaging implemented

### PR DESCRIPTION
**Pull request by pfelecan**
This is an implementation of the packaging for the **Debian** system.
For the moment it's done in a _native_ form, i.e. the _debianisation_ is embedded in the project.
Thus, it constitutes a base for someone willing to provide packages for **Debian** and also for those who are willing to become **Debian** maintainers for this package.

The salient points of the packaging are:

1. move the components of the package in the standard prefix, **/usr** instead of **/usr/local**
2. the Python components are moved to the correct distribution directory for **Debian**
3. a symbolic link, in post installation, is created toward the immutable **/usr/local/share/antimony/nodes** defined in **app/app/app.cpp**; it would be nice to have this as a parameter
4. provides a stub manual page

This passes **lintian** validation.

### CODE REVIEW

**Comment by mkeeter** [comment]
Cool!  Two quick requests:

I've made changes to make Antimony less sensitive to binary location (in [this thread](https://github.com/mkeeter/antimony/issues/152#issuecomment-230940845)).  These changes also include using `CMAKE_INSTALL_PREFIX` instead of hardcoding `/usr/local` and searching more widely for nodes and the Python files – can you rebase off of `develop` (or merge `develop` into your branch) and make sure that everything still works?

Can you copy these files to `deploy/linux/debian` instead of leaving them in the root of the repository?

**Comment by pfelecan** [comment]
For the first reques: yes, I'll do it
As for the second request I think, not 100% sure, that it's not possible as the **debian** directory must be in the projects root.

**Comment by pfelecan** [comment]
After resynchronization with the upstream/develop branch the packaging works without the need of specific actions for installation in the chosen prefix.
This is the answer to your first question.

**Comment by pfelecan** [comment]
As for your second question concerning the localization of the `debian` directory:

1. the packaging process needs a directory named `debian` , containing specific components, to exist in the project's root
2. however, if you wish so, we can move this directory in `deploy/linux/debian` and in the packaging instructions for this platform requests the creation of a symbolic link from the project's root directory to it.

What do you think ?

**Comment by mkeeter** [comment]
Okay, can you move the folder and add the symlink?

Once that's done, I'll merge this into `develop`

**Comment by pfelecan** [comment]
Alright. The only point is that I don't think that adding the symbolic link to the repository is a good thing. It would hinter the effort of an hypothetical, official,  Debian maintainer who'll need to have a true directory based on what I've done.
Its a little bit like the `build` directory, it's not in the repository; its creation is documented. Lets do the same for the `debian` symbolic link.

Agreed ?

**Comment by mkeeter** [comment]
Okay, looks good – thanks for setting this up!

**Pull request merged**
